// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adding_Facility_id_in_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding_Facility_id_in_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201803170502305_Adding_Facility_id_in_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
